[package]
name = "esperanto"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/Anaso-Internacia/esperanto"
description = "Utilities for working with Esperanto strings"

[dependencies]
